workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v6
      - node-v8
      - node-latest

version: 2
jobs:
  base: &base
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup wat2wasm
          command: |
            apt-get -y -qq update
            apt-get install -y cmake clang
            git submodule update --init --recursive
            cd deps/wabt && make && cd ../../
      - run:
          name: Setup sauce-connect
          command: |
            wget -o /usr/local/bin/sc https://saucelabs.com/downloads/sc-4.4.12-linux.tar.gz
            chmod +x /usr/local/bin/sc
            sc -h
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)

  node-v6:
    <<: *base
    docker:
      - image: node:6
  node-v8:
    <<: *base
    docker:
      - image: node:8
  node-latest:
    <<: *base
    docker:
      - image: node:latest
